### ISSUE TITLE
[TODO] doxygen style, graphviz

### ISSUE THREAD

**Issue by codeyoma** [42-MyMisters/42-MyMisters.github.io#2]
- [ ] doxygen
- [ ] graphviz

**Comment by codeyoma** [comment]
- [ ] jsdoc
- [ ] https://storybook.js.org/
- [ ] https://esdoc.org/
- [ ] https://github.com/slatedocs/slate
